Fix presubmit checks to work in a standalone checkout
This is necessary for the presubmit checks to work with the Commit
Queue, because the Commit Queue runs them in a standalone checkout.

Before this change, PRESUBMIT.py would fail with the following error
if not run from a directory called "native_client":

  ImportError: No module named code_hygiene

NaclTopDir() was broken and would print a warning but return a mangled
filename if the current directory did not contain the substring
"native_client", and it would therefore fail to modify sys.path to
point to the "tools" directory.

We remove the special handling that seems to be unnecessary given the
behaviour of git-cl and gcl.

Also remove the unused MAIN_DEPS variable.

BUG=http://code.google.com/p/chromium/issues/detail?id=158069
TEST=run "git cl presubmit"

Review URL: https://codereview.chromium.org/11336039

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@10143 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2