Update "trusted" chromium clang from 223108 to 233105.
Picked a version from late April, which is close to where NaCl/PNaCl's
branch is merged up to.

Need to fix printfs for -Wformat-pedantic.

Change Mac libdir search to hardcode the latest 3.X.0 clang dir
for dynamic linker, instead of including a glob of all of them.
Add a note to the DEPS file about updating that value.
For the most part, the update script should clobber the
directory so that only one choice is available, but the Mac Asan
trybot seems to fail at clobbering. Otherwise, with the glob, it
could end up picking an older version and get

dyld: Symbol not found: ___asan_init_v5
  Referenced from: /Volumes/data/b/build/slave/nacl/build/native_client/scons-out/opt-mac-x86-32/staging/sel_ldr
  Expected in: /Volumes/data/b/build/slave/nacl/build/third_party/llvm-build/Release+Asserts/lib/clang/3.6.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib

Change run_asan_test a bit (optimizations or something seem to be
throwing off the ability to catch naive bug -- O0 works, but O2
which the build scripts use, thwart asan). Does seem strange, but
we don't really control asan and they say:
"""Q: Why didn't ASan report an obviously invalid memory access in my code?
A1: If your errors is too obvious, compiler might have already optimized it out by the time Asan runs."""

Did not update all the way to the latest chromium clang.
The latest clang has -Wpessimizing-move, which requires
a bunch of more recent std::move fixes from upstream LLVM
(we use this to compile the PNaCl branch of LLVM),
so it would be a more complicated roll.

BUG=none
R=mcgrathr@chromium.org, mseaborn@chromium.org, phosek@chromium.org

Review URL: https://codereview.chromium.org/1259803006 .