Define __UINT_LEAST8_TYPE__ for toolchain tester.
After the newlib roll, commit 268f5ea02ed49b6b106bf702cf27275de20ef67a

 * libc/include/machine/_default_types.h: Define unsigned type using
   signed type macros in case unsigned type macros are not available.

We end up with "typedef unsigned signed char ...":
error: cannot combine with previous 'unsigned' declaration specifier [Parse Issue]
typedef unsigned __INT_LEAST8_TYPE__ __uint_least8_t;
                 ^
<command line>:4:29: note: expanded from here
  #define __INT_LEAST8_TYPE__ signed char
                              ^
1 error generated.

Clang and the older x86 nacl-gcc do not define __INT_LEAST8_TYPE__.
For now, since __INT_LEAST8_TYPE__ was only defined on the commandline,
also define __UINT_LEAST8_TYPE__ only from the commandline, so that
the newlib header doesn't try to use the fallback.

======

Also remove the -D__SIZEOF_INT__ , etc. since the compilers define those.

BUG=red toolchain bot
TEST=tools/toolchain_tester/torture_test.py pnacl x86-32 --verbose --concurrency=8

Review URL: https://codereview.chromium.org/323083003

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@13354 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2