Revert "build_nexe: Use thin archives when not stripping / not building SDK."
This reverts commit 9f29c7d5aa6d1216b36d2175b6db450eb1c44243.

Fails on Mac (too many file handles open), and Windows (relative paths
possibly create paths beyond max length for non-extended paths).

FAILED: E:\b\depot_tools\python276_bin\python.exe gyp-win-tool action-wrapper environment.x64 pnacl_hw_eh_disabled_test_target_build_newlib_pexe_1eb301ff09c5df5cf9febe560ebe8ed6..rsp ..\..\chrome\test\data\nacl
E:\b\build\slave\win\build\src\native_client\toolchain\win_x86\pnacl_newlib\bin\le32-nacl-ld.gold.exe:error: cannot open ../../../../out/Release_x64/gen/tc_pnacl_newlib/lib/../../../obj\native_client\src\untrusted\nacl\nacl_exception_private_lib.gen\pnacl_newlib-pnacl\nacl_exception_private_lib\nacl_exception_private_7bdc5a2f.o: No such file or directory

../../../../out/Release_x64/obj/chrome/test/data/nacl/pnacl_hw_eh_disabled_test.gen/pnacl_newlib/pnacl_hw_eh_disabled_test/pnacl_hw_eh_disabled_7e31384d.o:error: undefined reference to 'nacl_exception_clear_flag'

../../../../out/Release_x64/obj/chrome/test/data/nacl/pnacl_hw_eh_disabled_test.gen/pnacl_newlib/pnacl_hw_eh_disabled_test/pnacl_hw_eh_disabled_7e31384d.o:error: undefined reference to 'nacl_exception_set_stack'

../../../../out/Release_x64/obj/chrome/test/data/nacl/pnacl_hw_eh_disabled_test.gen/pnacl_newlib/pnacl_hw_eh_disabled_test/pnacl_hw_eh_disabled_7e31384d.o:error: undefined reference to 'nacl_exception_set_handler'

FAILED with 1: ..\..\..\..\native_client\toolchain\win_x86\pnacl_newlib\bin\pnacl-clang++ -o ..\..\..\..\out\Release_x64/nacl_test_data/pnacl/pnacl_hw_eh_disabled_newlib_pnacl.pexe.debug -Wl,--as-needed ..\..\..\..\out\Release_x64\obj\chrome\test\data\nacl\pnacl_hw_eh_disabled_test.gen/pnacl_newlib/pnacl_hw_eh_disabled_test\pnacl_hw_eh_disabled_7e31384d.o -B..\..\..\..\out\Release_x64/gen/tc_pnacl_newlib/lib -lppapi -lppapi_test_lib -lplatform -lgio -lnacl_exception_private -lppapi_cpp -lppapi -pthread -O3

ninja: build stopped: subcommand failed.

FAILED: cd ../../remoting; export BUILT_PRODUCTS_DIR=/Volumes/data/b/build/slave/mac/build/src/out/Release; export CONFIGURATION=Release; export PRODUCT_NAME=remoting_client_plugin_nacl; export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk; export SRCROOT=/Volumes/data/b/build/slave/mac/build/src/out/Release/../../remoting; export SOURCE_ROOT="${SRCROOT}"; export TARGET_BUILD_DIR=/Volumes/data/b/build/slave/mac/build/src/out/Release; export TEMP_DIR="${TMPDIR}";python ../native_client/build/build_nexe.py --root .. --product-dir ../out/Release/xyz --config-name Release -t ../native_client/toolchain/ --allow-thin-archives 1 --arch pnacl --build newlib_pexe --name ../out/Release/remoting_client_plugin_newlib.pexe --objdir ../out/Release/obj/remoting/remoting_client_plugin_nacl.gen/pnacl_newlib/remoting_client_plugin_nacl "--include-dirs=../out/Release/gen/tc_pnacl_newlib/include .. \"../out/Release/gen\" ../third_party/khronos ../gpu ../native_client_sdk/src/libraries ../native_client_sdk/src/libraries/nacl_io/include ../native_client_sdk/src/libraries/third_party/newlib-extras ../third_party/expat/files/lib ../third_party/icu/source/i18n ../third_party/icu/source/common ../third_party/libjingle/overrides ../third_party/libjingle/source ../third_party/webrtc/overrides ../third_party ../third_party/webrtc ../third_party/libyuv/include ../third_party/boringssl/src/include \"../out/Release/gen/protoc_out\" ../third_party/protobuf ../third_party/protobuf/src" "--compile_flags=-O2 -g -Wall -fdiagnostics-show-option -Werror  -gline-tables-only -Wno-unused-function -Wno-char-subscripts -Wno-c++11-extensions -Wno-unnamed-type-template-args -Wno-extra-semi -Wno-unused-private-field -Wno-char-subscripts -Wno-unused-function " --gomadir /Volumes/data/b/build/goma "--defines=\"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_DEFAULT_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=x86\" V8_DEPRECATION_WARNINGS \"__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0\" CHROMIUM_BUILD \"CR_CLANG_REVISION=223108\" \"USE_LIBJPEG_TURBO=1\" ENABLE_ONE_CLICK_SIGNIN ENABLE_PRE_SYNC_BACKUP \"ENABLE_REMOTING=1\" \"ENABLE_WEBRTC=1\" ENABLE_PEPPER_CDMS ENABLE_CONFIGURATION_POLICY ENABLE_NOTIFICATIONS \"ENABLE_HIDPI=1\" DISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY SYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE DONT_EMBED_BUILD_METADATA \"DCHECK_ALWAYS_ON=1\" \"ENABLE_TASK_MANAGER=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGIN_INSTALLATION=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_AUTOFILL_DIALOG=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_GOOGLE_NOW=1\" \"CLD_VERSION=2\" \"ENABLE_PRINTING=1\" \"ENABLE_BASIC_PRINTING=1\" \"ENABLE_PRINT_PREVIEW=1\" \"ENABLE_SPELLCHECK=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\" \"ENABLE_APP_LIST=1\" \"ENABLE_SETTINGS_APP=1\" \"ENABLE_SUPERVISED_USERS=1\" \"ENABLE_SERVICE_DISCOVERY=1\" \"ENABLE_WIFI_BOOTSTRAPPING=1\" V8_USE_EXTERNAL_STARTUP_DATA XML_STATIC \"U_USING_ICU_NAMESPACE=0\" \"U_ENABLE_DYLOAD=0\" U_STATIC_IMPLEMENTATION EXPAT_RELATIVE_PATH FEATURE_ENABLE_SSL GTEST_RELATIVE_PATH NO_MAIN_THREAD_WRAPPING NO_SOUND_SYSTEM POSIX WEBRTC_POSIX SRTP_RELATIVE_PATH SSL_USE_OPENSSL USE_WEBRTC_DEV_BRANCH GOOGLE_PROTOBUF_NO_RTTI GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER \"USE_LIBPCI=1\" \"USE_OPENSSL=1\" \"USE_OPENSSL_CERTS=1\" __STDC_CONSTANT_MACROS __STDC_FORMAT_MACROS" "--link_flags=-B../out/Release/gen/tc_pnacl_newlib/lib -O3 -lppapi_stub -lremoting_client_plugin_lib_nacl -lremoting_proto_nacl -ljingle_glue_nacl -lmedia_yuv_nacl -lnet_nacl -lcrypto_nacl -lbase_i18n_nacl -lbase_nacl -lurl_nacl -lremoting_webrtc_nacl -lyuv_nacl -lvpx_nacl -ljingle_p2p_constants_nacl -ljingle_nacl -lexpat_nacl -lmodp_b64_nacl -lopus_nacl -lboringssl_nacl -licui18n_nacl -licuuc_nacl -licudata_nacl -lprotobuf_lite_nacl -lppapi_cpp -lpthread -lnacl_io" "--source-list=../out/gypfiles/remoting/pnacl_newlib.remoting_client_plugin_nacl.source_list.gypcmd"
/Volumes/data/b/build/slave/mac/build/src/native_client/toolchain/mac_x86/pnacl_newlib/bin/le32-nacl-ld.gold: fatalerror: out of file descriptors and couldn't close any
FAILED with 1: ../native_client/toolchain/mac_x86/pnacl_newlib/bin/pnacl-clang++ -o ../out/Release/remoting_client_plugin_newlib.pexe.debug -Wl,--as-needed ../out/Release/obj/remoting/remoting_client_plugin_nacl.gen/pnacl_newlib/remoting_client_plugin_nacl/pepper_module_72e86210.o -B../out/Release/gen/tc_pnacl_newlib/lib -O3 -lppapi_stub -lremoting_client_plugin_lib_nacl -lremoting_proto_nacl -ljingle_glue_nacl -lmedia_yuv_nacl -lnet_nacl -lcrypto_nacl -lbase_i18n_nacl -lbase_nacl -lurl_nacl -lremoting_webrtc_nacl -lyuv_nacl -lvpx_nacl -ljingle_p2p_constants_nacl -ljingle_nacl -lexpat_nacl -lmodp_b64_nacl -lopus_nacl -lboringssl_nacl -licui18n_nacl -licuuc_nacl -licudata_nacl -lprotobuf_lite_nacl -lppapi_cpp -lpthread -lnacl_io
ninja: build stopped: subcommand failed.

BUG= https://code.google.com/p/chromium/issues/detail?id=454640
R=ncbray@chromium.org

Review URL: https://codereview.chromium.org/938563002